// Auto-generated by scripts/stats.sh — do not edit by hand.
window.__BLOG_DATA = {
  "generatedAt": "2026-05-09T22:34:34",
  "repoRoot": "/Users/rprp/Github-local/wrp-wrp.github.io",
  "posts": [
    {
      "slug": "2025-final",
      "path": "content/posts/2025-final/index.md",
      "title": "2025 Summary",
      "title_en": "",
      "summary": "Summary for rp's 2025 ",
      "date": "2026-02-16",
      "draft": false,
      "hidden": false,
      "tags": [],
      "categories": [],
      "wordCount": 535,
      "imageCount": 0,
      "mtime": 1778337193.417636
    },
    {
      "slug": "WasmVectorANNS",
      "path": "content/posts/WasmVectorANNS/index.md",
      "title": "WebAssembly and Vector Index for On-Device ANNS: Quantization Appears Sufficient",
      "title_en": "WebAssembly and Vector Index for On-Device ANNS: Quantization Appears Sufficient",
      "summary": "在端侧 ANNS 的内存约束下，量化索引 + 图搜索 + 小规模精排，走 diskann 路线看起来足够了。",
      "date": "2025-12-22",
      "draft": false,
      "hidden": false,
      "tags": [
        "WASM",
        "向量检索",
        "ANNS",
        "量化",
        "HNSW"
      ],
      "categories": [
        "技术调研"
      ],
      "wordCount": 812,
      "imageCount": 0,
      "mtime": 1775193332.4652843
    },
    {
      "slug": "TheoryOfComputation",
      "path": "content/posts/TheoryOfComputation/index.md",
      "title": "计算理论学习笔记",
      "title_en": "",
      "summary": "计算理论核心概念复习，涵盖自动机、可计算性与计算复杂性理论。",
      "date": "2025-11-26",
      "draft": true,
      "hidden": false,
      "tags": [
        "计算理论",
        "自动机",
        "图灵机",
        "复杂性"
      ],
      "categories": [
        "学习笔记"
      ],
      "wordCount": 12393,
      "imageCount": 0,
      "mtime": 1775197031.0263298
    },
    {
      "slug": "NetWorkReview",
      "path": "content/posts/NetWorkReview/index.md",
      "title": "NetWork Review Notes",
      "title_en": "",
      "summary": "",
      "date": "2025-11-20",
      "draft": false,
      "hidden": false,
      "tags": [],
      "categories": [],
      "wordCount": 15309,
      "imageCount": 4,
      "mtime": 1775197079.2588804
    }
  ],
  "totalWords": 16656,
  "totalDraftWords": 12393,
  "draftCount": 1,
  "hiddenCount": 0,
  "publishedCount": 3,
  "listedCount": 3,
  "tagCounts": {
    "WASM": 1,
    "向量检索": 1,
    "ANNS": 1,
    "量化": 1,
    "HNSW": 1
  },
  "months24": [
    "2024-06",
    "2024-07",
    "2024-08",
    "2024-09",
    "2024-10",
    "2024-11",
    "2024-12",
    "2025-01",
    "2025-02",
    "2025-03",
    "2025-04",
    "2025-05",
    "2025-06",
    "2025-07",
    "2025-08",
    "2025-09",
    "2025-10",
    "2025-11",
    "2025-12",
    "2026-01",
    "2026-02",
    "2026-03",
    "2026-04",
    "2026-05"
  ],
  "monthCounts": {
    "2026-02": 1,
    "2025-12": 1,
    "2025-11": 1
  },
  "inbox": [
    {
      "text": "(example) write a short note on streaming HNSW recall regression",
      "done": false,
      "raw": "- [ ] (example) write a short note on streaming HNSW recall regression"
    }
  ],
  "git": {
    "dirty": 47,
    "lines": [
      " M .github/workflows/hugo.yml",
      " M assets/css/custom.css",
      " M content/posts/2025-final/index.md",
      " M hugo.toml",
      " M layouts/_default/home.html",
      " M layouts/_default/single.html",
      " M layouts/partials/hooks/body_end.html",
      " M public/404.html",
      " M public/about/index.html",
      " M public/chat/index.html",
      " M public/index.html",
      " M public/index.xml",
      " M public/posts/2025-final/index.html",
      " M public/posts/index.html",
      " M public/posts/index.xml",
      " M public/posts/networkreview/index.html",
      " M public/posts/theoryofcomputation/index.html",
      " M public/posts/wasmvectoranns/index.html",
      " M public/resume/index.html",
      " M public/sitemap.xml",
      " M public/tags/anns/index.html",
      " M public/tags/hnsw/index.html",
      " M public/tags/index.html",
      " M public/tags/wasm/index.html",
      " M \"public/tags/\\345\\220\\221\\351\\207\\217\\346\\243\\200\\347\\264\\242/index.html\"",
      " M \"public/tags/\\345\\233\\276\\347\\201\\265\\346\\234\\272/index.html\"",
      " M \"public/tags/\\345\\244\\215\\346\\235\\202\\346\\200\\247/index.html\"",
      " M \"public/tags/\\350\\207\\252\\345\\212\\250\\346\\234\\272/index.html\"",
      " M \"public/tags/\\350\\256\\241\\347\\256\\227\\347\\220\\206\\350\\256\\272/index.html\"",
      " M \"public/tags/\\351\\207\\217\\345\\214\\226/index.html\""
    ]
  },
  "recent": [
    {
      "hash": "ff69584",
      "date": "2026-04-03",
      "msg": "blog: update posts"
    },
    {
      "hash": "176286b",
      "date": "2026-04-03",
      "msg": "blog: update posts"
    },
    {
      "hash": "7f0eeb1",
      "date": "2026-02-24",
      "msg": "revert: remove english learning section"
    },
    {
      "hash": "f0280e0",
      "date": "2026-02-23",
      "msg": "feat: add english learning section and template"
    },
    {
      "hash": "cf5182f",
      "date": "2026-02-20",
      "msg": "fix: update summary for 2025 to reflect author's perspective"
    },
    {
      "hash": "650fec5",
      "date": "2026-02-19",
      "msg": "1"
    },
    {
      "hash": "cef0d89",
      "date": "2026-02-19",
      "msg": "fix: correct SIGMOD benchmark author rank"
    },
    {
      "hash": "5595928",
      "date": "2026-02-19",
      "msg": "1"
    },
    {
      "hash": "95e955f",
      "date": "2026-02-19",
      "msg": "save"
    },
    {
      "hash": "be08d6a",
      "date": "2026-02-16",
      "msg": "chore: hide summary and theory posts"
    }
  ]
};
